### ISSUE TITLE
Unexpected Data frame from http request

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-http2.spec#10]
A single request with no payload into SourceInputStreamFactory is generating 3 nuklei frames.

1. Begin
2. Data
3. End

The Data and End are triggered by a nuklei data frame of : `DATA frame <length=0, flags=1, id=1>`
I would expect that as there are no headers and no data that a simple End frame would suffice. 

Thus also a spec test for this must be missing.

**Comment by jfallows** [comment]
Now resolved.
